{"name": "Неуспешная авторизация под несуществующим пользователем", "status": "passed", "steps": [{"name": "Заполняем \"Логин\" и \"Пароль\" случайными данными", "status": "passed", "start": 1718057431543, "stop": 1718057431543}], "start": 1718057431542, "stop": 1718057431736, "uuid": "14c2cd6c-c2b0-43cd-8f3a-2ac0272fe68e", "historyId": "f06036d6ca1305677e0f6cee446440f0", "testCaseId": "f06036d6ca1305677e0f6cee446440f0", "fullName": "tests.test_login.TestLogin#test_login_and_password_user_false", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "pavel-Inspiron-3501"}, {"name": "thread", "value": "10871-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}